apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: db-creds-volume
              mountPath: /usr/share/nginx/html/db-creds
      volumes:
        - name: db-creds-volume
          secret:
            secretName: db-creds

