apiVersion: v1
kind: Secret
metadata:
  name: db-creds
type: Opaque
data:
  username: cm9vdF91c2Vy # Base64 encoded "root_user"
  password: RXhwZXJ0cyExMjM= # Base64 encoded "Experts!123"
  database-url: bXlzcWwuc2VydmljZXMuY29t # Base64 encoded "mysql.services.com"

