# Default values for myfirstchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


deployment:
  name: avielb
  replicaCount: 3
  image:
    app: avielb/todo
    version: latest



service:
  name: avielb
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: