apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysql_deployment.name }}
  labels:
    app: {{ .Values.mysql_deployment.app_label }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.mysql_deployment.app_label }}
      tier: {{ .Values.mysql_deployment.tier }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.mysql_deployment.app_label }}
        tier: {{ .Values.mysql_deployment.tier }}
    spec:
      containers:
      - image: {{ .Values.mysql_deployment.image }}
        name: {{ .Values.mysql_deployment.name }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: wordpress
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: {{ .Values.mysql_deployment.container_port }}
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Values.mysql_pvc.name }}
