apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.wp_pvc.name }}
  labels:
    app: {{ .Values.wp_pvc.app_lable }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.wp_pvc.storage }}